language: node_js
node_js: node
services: postgresql
install:
- yarn
- yarn buildEnv
- yarn setup:server
- yarn setup:client

script:
- yarn build # develop with webpack
- yarn start:server # start the static webserver
